# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  integrationexternalcompany:
    image: integrationexternalcompany
    container_name: integrationexternalcompany
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 1320:1320
